language: node_js
addons:
  apt:
    packages:
      - language-pack-zh*
      - chinese*
      - fonts-wqy-microhei
      - ttf-wqy-microhei
      - fonts-wqy-zenhei
      - ttf-wqy-zenhei
before_script:
  - npm install -g gatsby-cli
  - npm install -g wait-on
node_js:
  - "12"
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - wip/preview
install: yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run serve &
  - wait-on http://localhost:9000
  - yarn run cypress:run --record
  - kill $(jobs -p) || true
deploy:
  - provider: script
    script: yarn run deploy
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: yarn run preview
    skip_cleanup: true
    on:
      branch: wip/preview
