language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
branches:
  only:
    - master
    - wip/preview
install: yarn install
deploy:
  - provider: script
    script: yarn run deploy
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: yarn run preview
    skip_cleanup: true
    on:
      branch: wip/preview
