language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4
      - language-pack-zh*
      - chinese*
      - fonts-wqy-microhei
      - ttf-wqy-microhei
      - fonts-wqy-zenhei
      - ttf-wqy-zenhei
node_js:
  - "12"
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - wip/preview
install: yarn install --frozen-lockfile
before_script:
  - npm install -g gatsby-cli
  - npm install -g start-server-and-test
script:
  - yarn run build:e2e
  - yarn run test:e2e:ci
  - yarn run clean
deploy:
  - provider: script
    script:
      - yarn run build
      - yarn run deploy
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script:
      - yarn run build
      - yarn run preview
    skip_cleanup: true
    on:
      branch: wip/preview
